version: 2
jobs:
  build:
    working_directory: /go/src/github.com/thomastaylor312/helm-commandeer
    docker:
      - image: circleci/golang:1.8.3
    steps:
      - checkout
      - run:
          name: Build release tarballs
          command: 'make dist'
      - store_artifacts:
          path: ./_dist
          destination: dist
      
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
